# Generated by Django 5.2.4 on 2025-08-06 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_contributor',
            new_name='contributors',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='issue_contributor',
        ),
        migrations.AddField(
            model_name='issue',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributed_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
