# Generated by Django 5.2.4 on 2025-08-06 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_project', '0002_rename_project_contributor_project_contributors_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='contributors',
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_user',
            field=models.ManyToManyField(blank=True, related_name='assigned_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
